#!/bin/bash

# check transmission status
transmission-remote -st &> /dev/null

if ! [[ $? -eq 0 ]]; then
    echo "Off"
    exit 0
fi

info=$(transmission-remote -st | grep -i "current session" -A 3 | tail -n3 | awk 'BEGIN { FS=":"}; { print $2 } ' | sed 's/\s//g')

up=$(echo "$info"| head -n1)
down=$(echo "$info" | head -n2 | tail -n1)
ratio=$(echo "$info" | tail -n1)

echo "up: $up | down: $down | r: $ratio"
