#!/bin/bash

list=$HOME/.backuplist.txt
source_dir=$HOME
destination="/mnt/hdd/backups/`hostname`-`date +%d_%m_%Y`.zip"

if [[ -n $1 ]]; then
    destination=$1
#    echo "USAGE: $0 [DESTINATION.zip]"
#   exit 1
fi

shopt -s extglob
cd $source_dir

ignore_list=()
for i in `grep -oE '^!.*' $list | cut -c 2-`; do
    ignore_list+=("$i")
done

include=$(grep -oE '^[^!]*' $list | strings -s ' ')
#ignore=
echo -e "INCLUDE:\n$include\n"
echo -e "IGNORE:\n${ignore_list[@]}\n"
#zip -r $destination $include -x "${ignore_list[@]}"
