#!/usr/bin/env python

import string
import sys
import random

chars = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!#$%&()*+,-./:;<=>?@[]^_`{|}~"

USAGE = "USAGE: genpass LENGTH"

length = 20

try:
    length = int(sys.argv[1])
except:
    pass

password = "".join([random.choice(chars) for _ in range(length)])
print(password)
