#!/bin/bash

wp_cfg="$HOME/.config/wallpaper"
wp_dir="/mnt/hdd/xd/pics/wallpapers"
def_wp="$wp_dir/default.webp"
new_wp="$def_wp"


wp_exists() {
    # exists ?
    if [[ -e $1 ]]; then
        echo `readlink -f $1`
    else
        # check inside wp_dir
        wpf="${wp_dir}/$1"
        if [[ -e $wpf ]]; then
            echo $wpf
        else
            # try to autocomplete
            wp_comp=$(find $wp_dir -iname ${1}* | head -n 1)
            if [[ -n $wp_comp ]]; then
                echo `readlink -f $wp_comp`
            else
                echo ""
            fi
        fi
    fi
}

# read wallpaper from input
if [[ -n "$1" ]]; then
    new_wp="$(wp_exists $1)"
# set from config
else
    if [[ -e $wp_cfg ]]; then
        new_wp=$(wp_exists $(head -n1 $wp_cfg))
    fi
fi

# set default if new wp doesnt exist
if [[ -z $new_wp ]]; then
    new_wp=$def_wp
fi

# update config
#   new_cfg=$(awk -v wp="$new_wp" 'BEGIN { FS="/"; OFS="/" }; { $5 = wp; print $0 }' $wp_cfg)
#  echo "$new_cfg" > $wp_cfg
echo "$new_wp" > $wp_cfg

# set new wallpaper
feh --bg-scale $new_wp

