#!/usr/bin/env python3

from urllib.parse import urlparse, parse_qs
import sys

USAGE = 'usage: urlparse URL'

try:
    url = sys.argv[1]
except:
    print(USAGE)
    sys.exit(1)


parsed = urlparse(url)
query = parse_qs(parsed.query, keep_blank_values=True)

info = {
        'scheme': parsed.scheme,
        'host': parsed.netloc,
        'path': parsed.path,
        'parameters': parsed.params,
        'query': ''
        }

pretty_len = max([len(i) for i in info])

for i in info:
    ws = ' ' * (pretty_len - len(i) + 1)
    print(i + ':' + ws + str(info[i]))

if len(query) > 0:
    # 12345 dsfdsf
    pretty_len = max([len(p) for p in query])
    prefix = ' ' * 4
    for p in query:
        ws = ' ' * (pretty_len - len(p) + 1)
        print(prefix + p + ':' + ws + query[p][0])

